# Generated by Django 3.0.6 on 2020-05-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_auto_20200505_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='searchrecord',
            old_name='category',
            new_name='category_info',
        ),
        migrations.RenameField(
            model_name='searchrecord',
            old_name='tracker',
            new_name='tracker_info',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='id',
            new_name='tracker_id',
        ),
    ]
