# Generated by Django 3.0.6 on 2020-05-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_auto_20200506_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
