# Generated by Django 3.0.6 on 2020-05-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0008_auto_20200506_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrecord',
            name='desc_url',
            field=models.CharField(default='', max_length=800),
            preserve_default=False,
        ),
    ]
