# Generated by Django 3.0.6 on 2020-05-07 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0010_auto_20200507_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('request', models.CharField(max_length=800, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='searchrecord',
            name='search_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_engine.SearchEvent'),
        ),
    ]
