# Generated by Django 3.0.6 on 2020-05-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0011_auto_20200507_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchevent',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchevent',
            name='request',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='searchrecord',
            name='search_event',
            field=models.ForeignKey(db_column='search_event', null=True, on_delete=django.db.models.deletion.CASCADE, to='search_engine.SearchEvent'),
        ),
    ]
