# Generated by Django 3.0.6 on 2020-05-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0012_auto_20200507_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrecord',
            name='age',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='searchrecord',
            name='category_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_engine.Category'),
        ),
        migrations.AlterField(
            model_name='searchrecord',
            name='tracker_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_engine.Tracker'),
        ),
    ]
